package org.omg.IOP;


/**
* org/omg/IOP/CodeSets.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-i586/jdk8u202/12319/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Saturday, December 15, 2018 12:00:24 PM PST
*/

public interface CodeSets
{

  /**
       * Identifies a CDR encapsulation of the 
       * <code>CONV_FRAME.CodeSetContext</code> defined in 
       * Section 13.10.2.5, "GIOP Code Set Service Context," on page 13-43.
       */
  public static final int value = (int)(1L);
}
