package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynSequence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-i586/jdk8u202/12319/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Saturday, December 15, 2018 12:00:24 PM PST
*/


/**
    * DynSequence objects support the manipulation of IDL sequences.
    */
public interface DynSequence extends DynSequenceOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity 
{
} // interface DynSequence
